#!/bin/bash
# Generate homepage graph-data.js from public Quartz content backlinks.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTENT="${1:-$ROOT/quartz/content}"
OUT="${2:-$ROOT/graph-data.js}"

# Hide private/asset-like nodes from the public graph.
BLOCK='3D|迁移|^附件|\.(png|jpe?g|webp|gif|svg|mp4)$'

python3 - "$CONTENT" "$OUT" "$BLOCK" <<'PY'
import sys, os, re, json

content, out, block = sys.argv[1], sys.argv[2], sys.argv[3]
blockre = re.compile(block) if block else None

published = set()
if os.path.isdir(content):
    for fn in os.listdir(content):
        if fn.endswith(".md") and fn != "index.md":
            published.add(fn[:-3])

def slug(name):
    return re.sub(r"\s+", "-", name.lower())

edges = []
nodes = {}

def add_node(name):
    if blockre and blockre.search(name):
        return False
    if name not in nodes:
        nodes[name] = {"id": name, "pub": name in published}
    return True

link_re = re.compile(r"\[\[([^\]]+)\]\]")
for fn in os.listdir(content):
    if not fn.endswith(".md") or fn == "index.md":
        continue
    src = fn[:-3]
    if not add_node(src):
        continue
    with open(os.path.join(content, fn), encoding="utf-8") as f:
        text = f.read()
    for match in link_re.finditer(text):
        target = match.group(1).split("|")[0].split("#")[0].strip()
        if not target:
            continue
        if not add_node(target):
            continue
        if src != target:
            edges.append([src, target])

seen = set()
links = []
for a, b in edges:
    key = tuple(sorted((a, b)))
    if key in seen:
        continue
    seen.add(key)
    links.append([a, b])

data = {
    "nodes": [{"id": n["id"], "pub": n["pub"], "slug": slug(n["id"])} for n in nodes.values()],
    "links": [{"source": a, "target": b} for a, b in links],
}

with open(out, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by Portfolio/scripts/gen-graph.sh\n")
    f.write("window.GRAPH_DATA = ")
    f.write(json.dumps(data, ensure_ascii=False, indent=0))
    f.write(";\n")

print(f"graph-data.js: {len(data['nodes'])} nodes / {len(data['links'])} links -> {out}")
PY
