// Auto-generated by Portfolio/scripts/gen-graph.sh
window.GRAPH_DATA = {
"nodes": [
{
"id": "DESIGN_核心系统设计文档",
"pub": true,
"slug": "design_核心系统设计文档"
},
{
"id": "DESIGN_世界观设计文档",
"pub": true,
"slug": "design_世界观设计文档"
},
{
"id": "DESIGN_玩家行为系统",
"pub": true,
"slug": "design_玩家行为系统"
},
{
"id": "DESIGN_能量系统",
"pub": true,
"slug": "design_能量系统"
},
{
"id": "DESIGN_光核与祭坛",
"pub": true,
"slug": "design_光核与祭坛"
},
{
"id": "DESIGN_天赋系统",
"pub": true,
"slug": "design_天赋系统"
},
{
"id": "DESIGN_天赋池设计",
"pub": true,
"slug": "design_天赋池设计"
},
{
"id": "DATA_天赋池",
"pub": true,
"slug": "data_天赋池"
},
{
"id": "策划案_光核与祭坛",
"pub": true,
"slug": "策划案_光核与祭坛"
},
{
"id": "DESIGN_模板",
"pub": false,
"slug": "design_模板"
},
{
"id": "策划案_项目基建",
"pub": true,
"slug": "策划案_项目基建"
},
{
"id": "INDEX_开发路线图",
"pub": true,
"slug": "index_开发路线图"
},
{
"id": "策划案_能量系统",
"pub": true,
"slug": "策划案_能量系统"
},
{
"id": "策划案_锈犬",
"pub": true,
"slug": "策划案_锈犬"
},
{
"id": "DESIGN_敌人系统",
"pub": true,
"slug": "design_敌人系统"
},
{
"id": "策划案_玩家行为系统",
"pub": true,
"slug": "策划案_玩家行为系统"
},
{
"id": "策划案_打击感与反馈",
"pub": false,
"slug": "策划案_打击感与反馈"
},
{
"id": "策划案_天赋系统",
"pub": true,
"slug": "策划案_天赋系统"
},
{
"id": "拆解_Dead Cells",
"pub": true,
"slug": "拆解_dead-cells"
},
{
"id": "拆解_Sekiro",
"pub": true,
"slug": "拆解_sekiro"
},
{
"id": "策划案_模板",
"pub": false,
"slug": "策划案_模板"
},
{
"id": "ART_原型表现规范与P0资源接入",
"pub": false,
"slug": "art_原型表现规范与p0资源接入"
},
{
"id": "策划案_原型表现系统",
"pub": false,
"slug": "策划案_原型表现系统"
},
{
"id": "ART_美术方向与资产规格",
"pub": true,
"slug": "art_美术方向与资产规格"
},
{
"id": "策划案_房间推进系统",
"pub": false,
"slug": "策划案_房间推进系统"
},
{
"id": "策划案_腐鹿",
"pub": false,
"slug": "策划案_腐鹿"
},
{
"id": "策划案_巡墙甲",
"pub": false,
"slug": "策划案_巡墙甲"
},
{
"id": "策划案_甲鼠",
"pub": false,
"slug": "策划案_甲鼠"
},
{
"id": "策划案_残弩",
"pub": false,
"slug": "策划案_残弩"
},
{
"id": "策划案_孢菇",
"pub": false,
"slug": "策划案_孢菇"
},
{
"id": "策划案_老骑士",
"pub": false,
"slug": "策划案_老骑士"
},
{
"id": "策划案_UI与游戏流程",
"pub": false,
"slug": "策划案_ui与游戏流程"
},
{
"id": "策划案_局流程管理",
"pub": false,
"slug": "策划案_局流程管理"
},
{
"id": "策划案_Meta成长系统",
"pub": false,
"slug": "策划案_meta成长系统"
},
{
"id": "策划案_异铸骑士",
"pub": false,
"slug": "策划案_异铸骑士"
},
{
"id": "策划案_年轻骑士",
"pub": false,
"slug": "策划案_年轻骑士"
},
{
"id": "策划案_游魂灯",
"pub": false,
"slug": "策划案_游魂灯"
},
{
"id": "策划案_铁罐",
"pub": false,
"slug": "策划案_铁罐"
},
{
"id": "策划案_残烛祭像",
"pub": false,
"slug": "策划案_残烛祭像"
},
{
"id": "策划案_商店系统",
"pub": false,
"slug": "策划案_商店系统"
},
{
"id": "策划案_随机事件",
"pub": false,
"slug": "策划案_随机事件"
},
{
"id": "策划案_美术规范",
"pub": false,
"slug": "策划案_美术规范"
},
{
"id": "策划案_数值平衡",
"pub": false,
"slug": "策划案_数值平衡"
},
{
"id": "ART_美术失败复盘",
"pub": true,
"slug": "art_美术失败复盘"
},
{
"id": "ART_P0美术尺寸规则",
"pub": false,
"slug": "art_p0美术尺寸规则"
},
{
"id": "ART_AI生图Prompt规范",
"pub": false,
"slug": "art_ai生图prompt规范"
},
{
"id": "Reforge 美术技术方案：两条路线对比",
"pub": false,
"slug": "reforge-美术技术方案：两条路线对比"
},
{
"id": "ART_攻击动画分层规范",
"pub": false,
"slug": "art_攻击动画分层规范"
}
],
"links": [
{
"source": "DESIGN_核心系统设计文档",
"target": "DESIGN_世界观设计文档"
},
{
"source": "DESIGN_核心系统设计文档",
"target": "DESIGN_玩家行为系统"
},
{
"source": "DESIGN_核心系统设计文档",
"target": "DESIGN_能量系统"
},
{
"source": "DESIGN_核心系统设计文档",
"target": "DESIGN_光核与祭坛"
},
{
"source": "DESIGN_核心系统设计文档",
"target": "DESIGN_天赋系统"
},
{
"source": "DESIGN_核心系统设计文档",
"target": "DESIGN_天赋池设计"
},
{
"source": "DESIGN_核心系统设计文档",
"target": "DATA_天赋池"
},
{
"source": "DESIGN_光核与祭坛",
"target": "DESIGN_能量系统"
},
{
"source": "DESIGN_光核与祭坛",
"target": "DESIGN_世界观设计文档"
},
{
"source": "DESIGN_光核与祭坛",
"target": "策划案_光核与祭坛"
},
{
"source": "DESIGN_光核与祭坛",
"target": "DESIGN_模板"
},
{
"source": "策划案_项目基建",
"target": "INDEX_开发路线图"
},
{
"source": "策划案_项目基建",
"target": "策划案_能量系统"
},
{
"source": "策划案_项目基建",
"target": "DESIGN_世界观设计文档"
},
{
"source": "策划案_锈犬",
"target": "DESIGN_敌人系统"
},
{
"source": "策划案_锈犬",
"target": "DESIGN_核心系统设计文档"
},
{
"source": "策划案_锈犬",
"target": "DESIGN_世界观设计文档"
},
{
"source": "策划案_锈犬",
"target": "INDEX_开发路线图"
},
{
"source": "策划案_锈犬",
"target": "策划案_玩家行为系统"
},
{
"source": "策划案_锈犬",
"target": "策划案_能量系统"
},
{
"source": "策划案_锈犬",
"target": "策划案_打击感与反馈"
},
{
"source": "策划案_能量系统",
"target": "DESIGN_能量系统"
},
{
"source": "策划案_能量系统",
"target": "DESIGN_核心系统设计文档"
},
{
"source": "策划案_能量系统",
"target": "INDEX_开发路线图"
},
{
"source": "策划案_能量系统",
"target": "策划案_玩家行为系统"
},
{
"source": "策划案_能量系统",
"target": "策划案_光核与祭坛"
},
{
"source": "策划案_能量系统",
"target": "策划案_天赋系统"
},
{
"source": "DESIGN_天赋系统",
"target": "DESIGN_玩家行为系统"
},
{
"source": "DESIGN_天赋系统",
"target": "DESIGN_能量系统"
},
{
"source": "DESIGN_天赋系统",
"target": "DESIGN_光核与祭坛"
},
{
"source": "DESIGN_天赋系统",
"target": "DESIGN_世界观设计文档"
},
{
"source": "DESIGN_天赋系统",
"target": "策划案_天赋系统"
},
{
"source": "DESIGN_天赋系统",
"target": "DESIGN_敌人系统"
},
{
"source": "DATA_天赋池",
"target": "DESIGN_天赋池设计"
},
{
"source": "DATA_天赋池",
"target": "DESIGN_天赋系统"
},
{
"source": "DATA_天赋池",
"target": "DESIGN_玩家行为系统"
},
{
"source": "DATA_天赋池",
"target": "DESIGN_能量系统"
},
{
"source": "DATA_天赋池",
"target": "DESIGN_光核与祭坛"
},
{
"source": "DATA_天赋池",
"target": "策划案_天赋系统"
},
{
"source": "DATA_天赋池",
"target": "INDEX_开发路线图"
},
{
"source": "拆解_Dead Cells",
"target": "DESIGN_核心系统设计文档"
},
{
"source": "拆解_Dead Cells",
"target": "DESIGN_玩家行为系统"
},
{
"source": "拆解_Dead Cells",
"target": "DESIGN_能量系统"
},
{
"source": "拆解_Dead Cells",
"target": "DESIGN_天赋系统"
},
{
"source": "拆解_Dead Cells",
"target": "DESIGN_光核与祭坛"
},
{
"source": "拆解_Dead Cells",
"target": "DATA_天赋池"
},
{
"source": "拆解_Dead Cells",
"target": "策划案_天赋系统"
},
{
"source": "策划案_光核与祭坛",
"target": "DESIGN_核心系统设计文档"
},
{
"source": "策划案_光核与祭坛",
"target": "DESIGN_世界观设计文档"
},
{
"source": "策划案_光核与祭坛",
"target": "INDEX_开发路线图"
},
{
"source": "策划案_光核与祭坛",
"target": "策划案_天赋系统"
},
{
"source": "策划案_光核与祭坛",
"target": "策划案_项目基建"
},
{
"source": "DESIGN_玩家行为系统",
"target": "INDEX_开发路线图"
},
{
"source": "DESIGN_玩家行为系统",
"target": "策划案_玩家行为系统"
},
{
"source": "DESIGN_玩家行为系统",
"target": "DESIGN_能量系统"
},
{
"source": "拆解_Sekiro",
"target": "DESIGN_玩家行为系统"
},
{
"source": "拆解_Sekiro",
"target": "策划案_玩家行为系统"
},
{
"source": "拆解_Sekiro",
"target": "策划案_锈犬"
},
{
"source": "拆解_Sekiro",
"target": "策划案_能量系统"
},
{
"source": "拆解_Sekiro",
"target": "DESIGN_天赋系统"
},
{
"source": "拆解_Sekiro",
"target": "DATA_天赋池"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_模板"
},
{
"source": "INDEX_开发路线图",
"target": "DESIGN_世界观设计文档"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_玩家行为系统"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_天赋系统"
},
{
"source": "INDEX_开发路线图",
"target": "ART_原型表现规范与P0资源接入"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_原型表现系统"
},
{
"source": "INDEX_开发路线图",
"target": "ART_美术方向与资产规格"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_房间推进系统"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_腐鹿"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_巡墙甲"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_甲鼠"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_残弩"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_孢菇"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_老骑士"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_UI与游戏流程"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_打击感与反馈"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_局流程管理"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_Meta成长系统"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_异铸骑士"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_年轻骑士"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_游魂灯"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_铁罐"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_残烛祭像"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_商店系统"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_随机事件"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_美术规范"
},
{
"source": "INDEX_开发路线图",
"target": "策划案_数值平衡"
},
{
"source": "DESIGN_天赋池设计",
"target": "DESIGN_天赋系统"
},
{
"source": "DESIGN_天赋池设计",
"target": "DESIGN_玩家行为系统"
},
{
"source": "DESIGN_天赋池设计",
"target": "DESIGN_能量系统"
},
{
"source": "DESIGN_天赋池设计",
"target": "策划案_天赋系统"
},
{
"source": "DESIGN_天赋池设计",
"target": "INDEX_开发路线图"
},
{
"source": "策划案_天赋系统",
"target": "DESIGN_光核与祭坛"
},
{
"source": "策划案_天赋系统",
"target": "策划案_玩家行为系统"
},
{
"source": "策划案_天赋系统",
"target": "策划案_锈犬"
},
{
"source": "ART_美术失败复盘",
"target": "ART_美术方向与资产规格"
},
{
"source": "ART_美术失败复盘",
"target": "ART_原型表现规范与P0资源接入"
},
{
"source": "ART_美术失败复盘",
"target": "ART_P0美术尺寸规则"
},
{
"source": "ART_美术失败复盘",
"target": "ART_AI生图Prompt规范"
},
{
"source": "ART_美术失败复盘",
"target": "Reforge 美术技术方案：两条路线对比"
},
{
"source": "ART_美术失败复盘",
"target": "INDEX_开发路线图"
},
{
"source": "策划案_玩家行为系统",
"target": "DESIGN_核心系统设计文档"
},
{
"source": "策划案_玩家行为系统",
"target": "策划案_项目基建"
},
{
"source": "策划案_玩家行为系统",
"target": "DESIGN_能量系统"
},
{
"source": "策划案_玩家行为系统",
"target": "策划案_打击感与反馈"
},
{
"source": "ART_美术方向与资产规格",
"target": "ART_原型表现规范与P0资源接入"
},
{
"source": "ART_美术方向与资产规格",
"target": "ART_P0美术尺寸规则"
},
{
"source": "ART_美术方向与资产规格",
"target": "ART_AI生图Prompt规范"
},
{
"source": "ART_美术方向与资产规格",
"target": "ART_攻击动画分层规范"
},
{
"source": "ART_美术方向与资产规格",
"target": "DESIGN_世界观设计文档"
},
{
"source": "DESIGN_敌人系统",
"target": "DESIGN_核心系统设计文档"
},
{
"source": "DESIGN_敌人系统",
"target": "DESIGN_世界观设计文档"
},
{
"source": "DESIGN_敌人系统",
"target": "DESIGN_玩家行为系统"
},
{
"source": "DESIGN_敌人系统",
"target": "DESIGN_能量系统"
},
{
"source": "DESIGN_敌人系统",
"target": "策划案_腐鹿"
},
{
"source": "DESIGN_敌人系统",
"target": "策划案_残弩"
},
{
"source": "DESIGN_敌人系统",
"target": "策划案_甲鼠"
},
{
"source": "DESIGN_敌人系统",
"target": "策划案_异铸骑士"
},
{
"source": "DESIGN_能量系统",
"target": "INDEX_开发路线图"
}
]
};
